
# Append subdirs with the list of subdirectories below any directory of dirs
macro(append_bil_directories dirs subdirs)
  #message("Entry in append_bil_directories!")
  #message("subdirs: ${subdirs}")
  #message("dirs: ${dirs}")
  unset(dirlist)
  foreach(dir ${dirs})
    #message("dir: ${dir}")
    unset(fulldir)
    unset(appdir)
    if(IS_ABSOLUTE ${dir})
      set(fulldir ${dir})
      set(appdir ${dir}/)
      #message("fulldir-1: ${fulldir}")
    elseif("${dir}" STREQUAL ".")
      set(fulldir ${CMAKE_CURRENT_SOURCE_DIR})
      set(appdir "")
      #message("fulldir-2: ${fulldir}")
    else()
      set(fulldir ${CMAKE_CURRENT_SOURCE_DIR}/${dir})
      set(appdir ${dir}/)
      #message("fulldir-3: ${fulldir}")
    endif()
    unset(list)
    file(GLOB list LIST_DIRECTORIES true RELATIVE ${fulldir} ${fulldir}/*)
    #file(GLOB list LIST_DIRECTORIES true ${fulldir}/*)
    #message("list: ${list}")
    foreach(it  ${list})
      if(IS_DIRECTORY ${fulldir}/${it})
        list(APPEND dirlist ${appdir}${it})
      endif()
    endforeach()
  endforeach()
  #message("dirlist: ${dirlist}")
  set(${subdirs} ${${subdirs}};${dirlist})
endmacro()
