
# Append src with the list of files below any directory of dirs. 
# Select files with the extension ext only.
macro(append_bil_files dirs ext src)
  foreach(dir ${dirs})
    #message("DIR: ${dir}")
    unset(fulldir)
    if(IS_ABSOLUTE ${dir})
      set(fulldir ${dir})
      #message("fulldir-1: ${fulldir}")
    elseif("${dir}" STREQUAL ".")
      set(fulldir ${CMAKE_CURRENT_SOURCE_DIR})
      #message("fulldir-2: ${fulldir}")
    else()
      set(fulldir ${CMAKE_CURRENT_SOURCE_DIR}/${dir})
      #message("fulldir-3: ${fulldir}")
    endif()
    unset(files)
    file(GLOB files LIST_DIRECTORIES false RELATIVE ${fulldir} ${fulldir}/*.${ext})
    #message("append_bil_files: files in ${dir}\n" "${files}" "\n")
    unset(var)
    foreach(file ${files})
      list(APPEND var ${dir}/${file})
    endforeach()
    #message("append_bil_files: var\n" "${var}" "\n")
    list(REMOVE_DUPLICATES var)
    set(${src} ${${src}};${var})
  endforeach()
  #message("append_bil_files: src\n" "${${src}}" "\n")
endmacro()

